RNSentry.podspec: remove hardcoded Folly version
getsentry/sentry-react-native pull request #2558
Opened 2022-10-19 14:12 UTC by miallo

This is done, because that makes it incompatible with react-native versions that hardcode a different version (e.g. 0.69.6)

Fixes #2557 

## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
Do not hardcode RCT-Folly version

## :bulb: Motivation and Context
This makes it compatible with a react-native version that uses a different Folly version. See #2557 

## :green_heart: How did you test it?
Manually patched the file in `node_modules`

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

2022-10-21 14:25 UTC, krystofwoldrich commented on RNSentry.podspec
> -folly_version = '2021.07.22.00'
Yes, definitely makes sense.

2022-10-21 16:23 UTC, krystofwoldrich requested changes
@miallo Thank you for fixing this. 

Could you update the changelog? After that, we can merge this.

```
## Unreleased

### Fixes

- Remove hardcoded Folly version ([#2558](https://github.com/getsentry/sentry-react-native/pull/2558))

```

2022-10-22 11:52 UTC, miallo commented
@krystofwoldrich Done :) I hope it is all right :)

2022-10-24 07:47 UTC, krystofwoldrich approved these changes

2022-10-24 09:55 UTC, merged