ignore start spam if too slow
getsentry/sentry-react-native pull request #3299
Opened 2023-09-21 14:56 UTC by lucas-zimerman

## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring

## :scroll: Description

## :bulb: Motivation and Context

Fixes #[3044](https://github.com/getsentry/sentry-react-native/issues/3044) / Long span messing the measures of alerts.

## :green_heart: How did you test it?

froze app start and released after the timeout. Before and after  this change can be seen on the following transactions:

https://sentry-sdks.sentry.io/discover/sentry-react-native:6fbe53e73d9048c194169f1228a1bd55/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&id=21705&name=&project=5428561&query=&sort=-timestamp&statsPeriod=1h&topEvents=5&yAxis=count()

https://sentry-sdks.sentry.io/discover/sentry-react-native:c764f2fd956e40349e79434d98bcb4ff/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&id=21705&name=&project=5428561&query=&sort=-timestamp&statsPeriod=1h&topEvents=5&yAxis=count()

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [ ] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps

2023-09-21 15:01 UTC, lucas-zimerman commented
@krystofwoldrich the transaction will look different on the cases where this issue was happening, is this considered a break change?

2023-09-25 10:18 UTC, krystofwoldrich commented
@lucas-zimerman Yes, they are different, but I believe this should be a **fix**, as over minute start-up span is definitely a bug.

2023-09-25 10:34 UTC, krystofwoldrich requested changes
This looks good and removes the app start spans longer than the threshold, but the overall transaction is still the same length as the start span would be included. Which I believe is unwanted.

These two transaction start times should be also inside the threshold condition in the `_addAppStartData` method.

https://github.com/getsentry/sentry-react-native/blob/9fce5368945d79430c72cc697041e7c1b6767f3e/src/js/tracing/reactnativetracing.ts#L360

https://github.com/getsentry/sentry-react-native/blob/9fce5368945d79430c72cc697041e7c1b6767f3e/src/js/tracing/reactnativetracing.ts#L469

2023-10-09 09:15 UTC, krystofwoldrich commented on src/js/tracing/reactnativetracing.ts
> +import { logger, timestampInSeconds } from '@sentry/utils';
```suggestion
import { logger } from '@sentry/utils';
```

2023-10-09 09:17 UTC, krystofwoldrich commented on src/js/tracing/reactnativetracing.ts
> +    if (!appStartDurationMilliseconds) {
```suggestion
  ): void {
    const appStartDurationMilliseconds = this._getAppStartDurationMilliseconds(appStart);
    if (!appStartDurationMilliseconds) {
```

2023-10-09 09:18 UTC, krystofwoldrich commented on src/js/tracing/reactnativetracing.ts
```suggestion

    transaction.startTimestamp = appStartTimeSeconds;

```

2023-10-09 09:18 UTC, krystofwoldrich commented on src/js/tracing/reactnativetracing.ts
> +        this._addAppStartData(transaction, this._awaitingAppStartData, appStartDurationMilliseconds);
```suggestion
        transaction.op = UI_LOAD;
        this._addAppStartData(transaction, this._awaitingAppStartData);
```

2023-10-09 09:19 UTC, krystofwoldrich commented on test/tracing/reactnativetracing.test.ts
> +        }
```suggestion

          expect(
            transaction.startTimestamp
          ).toBeGreaterThanOrEqual(timeOriginMilliseconds/1000);
        }
```

2023-10-09 09:28 UTC, krystofwoldrich commented on src/js/tracing/reactnativetracing.ts
```suggestion
```

2023-10-09 09:28 UTC, krystofwoldrich commented on src/js/tracing/reactnativetracing.ts
> +        this._addAppStartData(idleTransaction, appStart, appStartDurationMilliseconds);
```suggestion
        this._addAppStartData(idleTransaction, appStart);
```

2023-10-09 09:30 UTC, krystofwoldrich commented
@lucas-zimerman Thanks for the update, now the transactions have the correct start timestamp when the app start time is not added. 👍

I just have a few suggestions on how to avoid checking the duration at 3 different places. I believe we can do use the one check in the `addAppStartData` function.

2023-10-09 12:12 UTC, krystofwoldrich approved these changes

2023-10-09 15:43 UTC, merged